"""fix_relationships

Revision ID: 2ee92e40113e
Revises: 4126dd3752a9
Create Date: 2025-07-31 13:28:19.131677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ee92e40113e'
down_revision: Union[str, Sequence[str], None] = '4126dd3752a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('user_achievements', 'user_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=True)
    op.drop_constraint(op.f('fk_user_stats_user_id'),
                       'user_stats', type_='foreignkey')
    op.create_foreign_key(None, 'user_stats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_stats_user_id'), 'user_stats', 'users', [
                          'user_id'], ['id'], ondelete='CASCADE')
    # op.alter_column('user_achievements', 'user_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###
