"""Fix relationships between Task and Theory

Revision ID: 4124def56530
Revises: a740b916aae3
Create Date: 2025-07-26 20:06:18.612649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4124def56530'
down_revision: Union[str, Sequence[str], None] = 'a740b916aae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('task_id'), table_name='theories')
    op.drop_constraint(op.f('theories_ibfk_3'), 'theories', type_='foreignkey')
    op.drop_column('theories', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theories', sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('theories_ibfk_3'), 'theories', 'tasks', ['task_id'], ['id'])
    op.create_index(op.f('task_id'), 'theories', ['task_id'], unique=True)
    # ### end Alembic commands ###
